---
ansible_user: wakacau
systemd_dir: /etc/systemd/system
zookeeper_host: "{{ hostvars[groups['zookeeper'][0]]['ansible_host'] | default(groups['zookeeper'][0]) }}"

# Zookeeper Config
zookeeper_data_dir: /tmp/zookeeper
zookeeper_port: 2181
zookeeper_max_client_cnxns: 0
zookeeper_enable_admin_server: false
zookeeper_admin_port: 2105

# Kafka Config
kafka_version: 2.7.0
kafka_scala_version: 2.13
kafka_download_url: https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
kafka_root_dir: /opt
kafka_config_dir: /etc/kafka
kafka_dir: "{{ kafka_root_dir }}/kafka"
kafka_main_dir: "{{ kafka_dir }}_{{ kafka_scala_version }}-{{ kafka_version }}"
kafka_broker_id: 0
kafka_network_threads: 3
kafka_num_io_threads: 8
kafka_logs_dir: /var/lib/kafka/logs
kafka_num_partitions: 1
kafka_retention_hours: 168

kafka_zookeeper_connect: "{{ zookeeper_host }}:{{ zookeeper_port }}"
kafka_zookeeper_timeout_ms: 18000
