---
- name: Check if Kafka has already been downloaded and unpacked
  become: true
  stat:
    path: "{{ kafka_main_dir }}"
  register: dir

- name: Download Apache Kafka
  get_url:
    url: "{{ kafka_download_url }}"
    dest: /tmp
  when: not dir.stat.exists
  tags:
    - kafka_download

- name: Unpack Apache Kafka
  become: true
  unarchive:
    src: /tmp/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz
    dest: "{{ kafka_root_dir }}"
    copy: no
    owner: "{{ ansible_user }}"
  when: not dir.stat.exists
  tags:
    - kafka_unpack

- name: Make Kafka Config folder
  become: true
  file:
    path: "{{ kafka_config_dir }}"
    owner: root
    group: root
    mode: 0775
    state: directory
