---
- name: Copy Kafka config
  become: true
  template:
    src: server.properties.j2
    dest: "{{ kafka_config_dir }}/server.properties"
    owner: root
    group: root
    mode: 0755

- name: Make Kafka logs folder
  become: true
  file:
    path: "{{ kafka_logs_dir }}"
    recurse: true
    owner: "{{ ansible_user }}"
    group: root
    mode: 0775
    state: directory

- name: Copy Kafka Services
  become: true
  template:
    src: "kafka.service.j2"
    dest: "{{ systemd_dir }}/kafka.service"
    owner: root
    group: root
    mode: 0755

- name: Enable and check Kafka service
  become: true
  systemd:
    name: kafka
    daemon_reload: yes
    state: restarted
    enabled: yes
    force: true
